name: Terraform Plan

on:
  pull_request:
    branches:
      - main  # Specify the branch(es) you want this workflow to trigger on

jobs:
  save-pr-number:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Save the PR number in a file
      - name: Save the PR number in an artifact
        run: echo "123\\nTEST=BLA" > pr_num.txt
      # Step 3: Upload the PR number artifact
      - name: Upload the PR number artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_num
          path: pr_num.txt
